//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demande
    {
        public int Id { get; set; }
        public string Motif { get; set; }
        public string Statut { get; set; }
        public string Info { get; set; }
        public string Email { get; set; }
        public Nullable<int> IdSalarie { get; set; }
    
        public virtual Salary Salary { get; set; }
    }
}
